[tools]
act = "latest"
dotnet = "7.0.410"

[env]
_.path = [
    # adds an absolute path
    "~/.local/share/bin",
    # adds paths relative to directory in which this file was found (see below for details), not PWD
    "{{config_root}}/node_modules/.bin",
    # adds paths relative to the exact file that this is found in (not PWD)
    "tools/bin",
]
GODOT4 = { tools = true, value = "{{ exec(command='which godot') }}" }
