name: Make Zip File
description: Zips up files matching specified path globs

inputs:
  path-globs:
    description: A newline-separated list of path globs to include in the zip
    required: true
  output-file:
    description: The name of the output zip file (without .zip extension)
    required: false
    default: "archive"

outputs:
  zip-path:
    description: The path to the created zip file
    value: ${{ steps.zip.outputs.zip-path }}

runs:
  using: composite
  steps:
    - name: Validate input paths
      id: validate
      shell: bash
      run: |
        # Convert newline-separated globs to an array
        IFS=$'\n' read -r -d '' -a GLOBS <<< "${{ inputs.path-globs }}"
        if [ ${#GLOBS[@]} -eq 0 ]; then
          echo "Error: No path globs provided"
          exit 1
        fi
        # Check if at least one file matches the globs
        FOUND=false
        for GLOB in "${GLOBS[@]}"; do
          if compgen -G "$GLOB" > /dev/null; then
            FOUND=true
            break
          fi
        done
        if [ "$FOUND" = "false" ]; then
          echo "Error: No files match the provided globs: ${{ inputs.path-globs }}"
          exit 1
        fi
        echo "valid=true" >> $GITHUB_OUTPUT

    - name: Zip the files
      id: zip
      shell: bash
      run: |
        # Convert newline-separated globs to space-separated for zip command
        PATHS=$(echo "${{ inputs.path-globs }}" | tr '\n' ' ')
        ZIP_FILE="${{ inputs.output-file }}.zip"
        # Zip the files matching the globs
        zip -r "$ZIP_FILE" $PATHS
        echo "zip-path=$ZIP_FILE" >> $GITHUB_OUTPUT
