name: Pr

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  issues: write
  pull-requests: write
  actions: read
  contents: read
  statuses: write # read/write to repo custom statuses

jobs:
  Check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 #v3
        with:
          fetch-depth: 0

      - uses: jdx/mise-action@5bb8f8c1911837cf42064e6490e7634fc842ee7e # v2
        env:
          GITHUB_API_TOKEN: ${{ secrets.ASDF_GITHUB_API_TOKEN }}
        with:
          version: 2025.2.7

      - name: Setup Godot Project
        uses: ./.github/actions/setup-godot-project

      - name: 🦺 Build
        run: mise run build --platform linux --debug --clean
