name: Release

on:
  push:
    branches:
      - master

env:
  HUSKY: 0 # https://typicode.github.io/husky/how-to.html#ci-server-and-docker

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  actions: read
  contents: write
  issues: write
  deployments: write
  pull-requests: write
  id-token: write

jobs:
  Process:
    runs-on: ubuntu-latest
    outputs:
      tagname: ${{ steps.release-please.outputs.tag_name }}
      releases_created: ${{ steps.release-please.outputs.releases_created }}
      prs_created: ${{ steps.release-please.outputs.prs_created }}
      prs: ${{ steps.release-please.outputs.prs }}
      pr: ${{ steps.release-please.outputs.pr }}
      sha: ${{ steps.release-please.outputs.sha }}
    steps:
      - uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f #v4
        id: release-please
        with:
          token: ${{secrets.ZENOBIUS_MONOREPO_RELEASE_PLEASE_TOKEN}}
          release-type: node
      - name: Print Release Data
        run: |
          echo 'Release Data:'

          echo '''
            ${{ toJSON(steps.release-please.outputs) }}
          '''

  Deploy:
    needs: Process
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 #v3
        with:
          fetch-depth: 0

      - uses: jdx/mise-action@5bb8f8c1911837cf42064e6490e7634fc842ee7e # v2
        env:
          GITHUB_API_TOKEN: ${{ secrets.ASDF_GITHUB_API_TOKEN }}
        with:
          version: 2024.11.4

      - name: Setup Godot Project
        uses: ./.github/actions/setup-godot-project

      - name: Super-linter
        uses: super-linter/super-linter@85f7611e0f7b53c8573cca84aa0ed4344f6f6a4d #v7.2.1
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🦺 Build
        run: dotnet build

      - if: ${{ needs.Process.outputs.releases_created == 'true' }}
        id: production-deployment
        run: |
          echo "public build"
          gh release upload ${{ needs.Process.outputs.tagname }} ./dist/bin

      - if: ${{ needs.Process.outputs.prs_created == 'true' }}
        id: development-deployment
        run: |
          echo "dev build"
