name: Release

on:
  push:
    branches:
      - master

env:
  HUSKY: 0 # https://typicode.github.io/husky/how-to.html#ci-server-and-docker

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  actions: read
  contents: write
  issues: write
  deployments: write
  pull-requests: write
  id-token: write

jobs:
  Process:
    runs-on: ubuntu-latest
    outputs:
      tagname: ${{ steps.release-please.outputs.tag_name }}
      releases_created: ${{ steps.release-please.outputs.releases_created }}
      prs_created: ${{ steps.release-please.outputs.prs_created }}
      prs: ${{ steps.release-please.outputs.prs }}
      pr: ${{ steps.release-please.outputs.pr }}
      sha: ${{ steps.release-please.outputs.sha }}
    steps:
      - uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f #v4
        id: release-please
        with:
          token: ${{secrets.ZENOBIUS_MONOREPO_RELEASE_PLEASE_TOKEN}}
          release-type: node
      - name: Print Release Data
        run: |
          echo 'Release Data:'

          echo '''
            ${{ toJSON(steps.release-please.outputs) }}
          '''

  Deploy:
    needs: Process
    if: ${{ needs.Process.outputs.releases_created == 'true' }}
    strategy:
      matrix:
        include:
          - on: ubuntu-latest
            platform: linux
          # - on: windows-latest
          #   platform: windows
          # - on: macos-latest
          #   platform: macos

    runs-on: "${{ matrix.on }}"

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 #v3
        with:
          fetch-depth: 0

      - uses: jdx/mise-action@5bb8f8c1911837cf42064e6490e7634fc842ee7e # v2
        env:
          GITHUB_API_TOKEN: ${{ secrets.ASDF_GITHUB_API_TOKEN }}

      - name: Setup Godot Project
        uses: ./.github/actions/setup-godot-project

      - name: Build
        run: |
          mise run build \
            --release \
            --platform "${{ matrix.platform }}" \
            --clean

      - name: Zip the dist/bin directory
        id: zip-dir
        uses: ./.github/actions/zip-directory
        with:
          path-globs: |
            ./dist/${{ matrix.platform }}/*
          output-file: "${{ matrix.platform }}-game"

      - uses: ./.github/actions/upload-release
        with:
          tagname: "${{needs.Process.outputs.tagname}}"
          filepath: "${{ steps.zip-dir.outputs.zip-path }}"
